name: Distribute extension
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
   build:
       runs-on: ubuntu-latest
       name: Deploy to satispress
       steps:
           - name: Checkout code
             uses: actions/checkout@v4
           - name: Install Node.js
             uses: actions/setup-node@v4
             with:
               node-version: 18.x
           - name: Publish
             run: npm run deploy
             env:
               VSCE_PAT: ${{ secrets.VSCE_PAT }}